### ISSUE TITLE
ztest: support multiple test definitions in one .yaml file

### ISSUE THREAD

**Issue by henridf** [brimsec/zq#849]
The tests in proc/groupby_test.go would be individually more readable as yaml, but as a whole less understandable if split across 15 files, which is what would result if we ported them right now. This issue is also applicable to existing yaml test dirs such as tests/suite/put containing many single-test files with unhelpful names.

An improvement would be to allow multiple tests in one yaml file, with a layout like:

```yaml
put-multi-1:
  zql: put a=b, b=a
  input: |
    #0:record[x:int32]
    0:[1;]
    0:[2;]
  output: |
    ...
put-multi-2:
  zql: put a=b, b=a
  input: |
    ...
  output: |
    ...
```
